format_version: "3.0.2"
name: prometheus_input
title: "Prometheus Input"
version: "0.9.0"
description: "Collects metrics from Prometheus exporter."
type: input
categories:
  - monitoring
  - containers
  - custom
  - observability
conditions:
  kibana:
    version: "^8.13.0 || ^9.0.0"
  elastic:
    subscription: "basic"
icons:
  - src: /img/logo_prometheus.svg
    title: logo prometheus
    size: 32x32
    type: image/svg+xml
policy_templates:
  - name: prometheus
    type: metrics
    title: Prometheus Metrics
    description: Collects Prometheus Metrics
    input: prometheus/metrics
    template_path: input.yml.hbs
    vars:
      - name: hosts
        type: text
        title: Hosts
        multi: true
        required: true
        show_user: true
        default:
          - localhost:9090/metrics
      - name: period
        type: text
        title: Period
        multi: false
        required: true
        show_user: true
        default: 10s
      - name: use_types
        type: bool
        title: Use Types
        multi: false
        required: true
        show_user: true
        default: true
      - name: rate_counters
        type: bool
        title: Rate Counters
        multi: false
        required: true
        show_user: true
        default: true
      - name: metrics_filters.exclude
        type: text
        title: Metrics Filters Exclude
        multi: true
        required: false
        show_user: false
        default: []
      - name: metrics_filters.include
        type: text
        title: Metrics Filters Include
        multi: true
        required: false
        show_user: false
        default: []
      - name: ssl.verification_mode
        type: text
        title: SSL Verification Mode
        description: SSL verification mode. See [documentation](https://www.elastic.co/guide/en/beats/metricbeat/current/configuration-ssl.html#client-verification-mode) for details.
        multi: false
        required: false
        show_user: false
        default: none  
      - name: ssl.certificate_authorities
        type: text
        title: SSL Certificate Authorities
        description: SSL Certificate Authorities. See [documentation](https://www.elastic.co/guide/en/beats/metricbeat/current/configuration-ssl.html#client-certificate-authorities) for details.
        multi: true
        required: false
        show_user: false
      - name: ssl.certificate
        type: text
        title: SSL Certificate
        description: SSL certificate. See [documentation](https://www.elastic.co/guide/en/beats/metricbeat/current/configuration-ssl.html#client-certificate) for details.
        show_user: true
      - name: ssl.key
        type: text
        title: SSL Private Key
        description: SSL private key. See [documentation](https://www.elastic.co/guide/en/beats/metricbeat/current/configuration-ssl.html#client-key) for details.
        show_user: true
      - name: ssl.key_passphrase
        type: password
        title: SSL Key Passphrase
        description: SSL key passphrase. See [documentation](https://www.elastic.co/guide/en/beats/metricbeat/current/configuration-ssl.html#client-key-passphrase) for details.
        secret: true
        show_user: true
      - name: ssl.ca_trusted_fingerprint
        type: text
        title: SSL CA Trusted Fingerprint
        description: SSL CA trusted fingerprint. See [documentation](https://www.elastic.co/guide/en/beats/metricbeat/current/configuration-ssl.html#ca_trusted_fingerprint) for details.
        show_user: true  
      - name: username
        type: text
        title: Username
        multi: false
        required: false
        show_user: true
      - name: password
        type: password
        title: Password
        secret: true
        multi: false
        required: false
        show_user: true
      - name: data_stream.dataset
        type: text
        title: 'Datastream Dataset name'
        description: Name of Datastream dataset
        multi: false
        default: prometheus
        required: true
        show_user: true
      - name: leaderelection
        type: bool
        title: Leader Election
        description: Enable leaderelection between a set of Elastic Agents running on Kubernetes. See [Kubernetes LeaderElection Provider](https://www.elastic.co/guide/en/fleet/current/kubernetes_leaderelection-provider.html) for details.
        multi: false
        required: true
        show_user: true
        default: false
      - name: condition
        title: Condition
        description: Condition to filter when to collect this input. See [Dynamic Input Configuration](https://www.elastic.co/guide/en/fleet/current/dynamic-input-configuration.html) for details.
        type: text
        multi: false
        required: false
        show_user: true
      - name: bearer_token_file
        type: text
        title: 'HTTP config options: bearer_token_file'
        description: If defined, the contents of the file will be read once at initialization and then the value will be used in an HTTP Authorization header.
        multi: false
        secret: false
        required: false
        show_user: false  
      - name: processors
        type: yaml
        title: Processors
        multi: false
        required: false
        show_user: false
        description: >
          Processors are used to reduce the number of fields in the exported event or to enhance the event with metadata. This executes in the agent before the events are shipped. See [Processors](https://www.elastic.co/guide/en/fleet/current/elastic-agent-processor-configuration.html) for details.  
owner:
  github: elastic/obs-infraobs-integrations
  type: elastic
